<?php 
$hostname="localhost";
$database="android";
$username="esneyder";
$password="123";
$localhost=mysql_connect($hostname,$username,$password)
or  
trigger_error(mysql_error(),E_USER_ERROR);
mysql_select_db($database,$localhost);
 ?>